#pragma once

#include <cstddef>

#include "config/pins.h"

namespace TankRC::Config {
struct PinSchemaEntry {
    const char* board;
    const char* path;
    const char* token;
    const char* label;
    const char* owner;
    const char* description;
    const char* type;
    const char* hint;
    bool allowPcf;
    bool gpioOnly;
    int defaultPin;
    int minValue;
    int maxValue;
};

constexpr PinSchemaEntry kPinSchema[] = {
    {"master", "pins.leftDriver.motorA.pwm", "leftMotorA_pwm", "Left motor A PWM",
     "Left driver PWM", "Speed output for the front-left track.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::LEFT_MOTOR1_PWM, 0, 39},
    {"master", "pins.leftDriver.motorA.in1", "leftMotorA_in1", "Left motor A IN1",
     "Left driver direction", "Direction input A for the front-left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR1_IN1, 0, 39},
    {"master", "pins.leftDriver.motorA.in2", "leftMotorA_in2", "Left motor A IN2",
     "Left driver direction", "Direction input B for the front-left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR1_IN2, 0, 39},
    {"master", "pins.leftDriver.motorB.pwm", "leftMotorB_pwm", "Left motor B PWM",
     "Left driver PWM", "Speed output for the rear-left track.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::LEFT_MOTOR2_PWM, 0, 39},
    {"master", "pins.leftDriver.motorB.in1", "leftMotorB_in1", "Left motor B IN1",
     "Left driver direction", "Direction input A for the rear-left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR2_IN1, 0, 39},
    {"master", "pins.leftDriver.motorB.in2", "leftMotorB_in2", "Left motor B IN2",
     "Left driver direction", "Direction input B for the rear-left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR2_IN2, 0, 39},
    {"master", "pins.leftDriver.standby", "leftDriver_stby", "Left driver standby",
     "Left driver", "Standby pin used to enable the TB6612 driver.", "Digital output", "GPIO-only driver enable.",
     false, true, Pins::LEFT_DRIVER_STBY, 0, 39},
    {"master", "pins.rightDriver.motorA.pwm", "rightMotorA_pwm", "Right motor A PWM",
     "Right driver PWM", "Speed output for the front-right track.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::RIGHT_MOTOR1_PWM, 0, 39},
    {"master", "pins.rightDriver.motorA.in1", "rightMotorA_in1", "Right motor A IN1",
     "Right driver direction", "Direction input A for the front-right track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR1_IN1, 0, 39},
    {"master", "pins.rightDriver.motorA.in2", "rightMotorA_in2", "Right motor A IN2",
     "Right driver direction", "Direction input B for the front-right track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR1_IN2, 0, 39},
    {"master", "pins.rightDriver.motorB.pwm", "rightMotorB_pwm", "Right motor B PWM",
     "Right driver PWM", "Speed output for the rear-right track.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::RIGHT_MOTOR2_PWM, 0, 39},
    {"master", "pins.rightDriver.motorB.in1", "rightMotorB_in1", "Right motor B IN1",
     "Right driver direction", "Direction input A for the rear-right track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR2_IN1, 0, 39},
    {"master", "pins.rightDriver.motorB.in2", "rightMotorB_in2", "Right motor B IN2",
     "Right driver direction", "Direction input B for the rear-right track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR2_IN2, 0, 39},
    {"master", "pins.rightDriver.standby", "rightDriver_stby", "Right driver standby",
     "Right driver", "Standby pin used to enable the right TB6612 driver.", "Digital output", "GPIO-only driver enable.",
     false, true, Pins::RIGHT_DRIVER_STBY, 0, 39},
    {"master", "pins.lightBar", "light_pin", "Light bar PWM",
     "Lighting module", "Drives the PCA9685 channel that feeds the front/rear light clusters.", "Lighting", "GPIO or PCA pin.",
     true, false, Pins::LIGHT_BAR, 0, 39},
    {"master", "pins.speaker", "speaker_pin", "Sound output",
     "Sound FX", "Speaker output used by the sound controller.", "Audio output", "GPIO or PCA pin.",
     true, false, Pins::SPEAKER, 0, 39},
    {"master", "pins.batterySense", "battery_pin", "Battery sense",
     "Battery monitor", "Analog pin used to measure the battery voltage.", "Analog input", "GPIO or PCA pin.",
     true, false, Pins::BATTERY_SENSE, 0, 39},
    {"master", "pins.pcfAddress", "pcfAddress", "PCF8575 address",
     "IO expander", "I2C address for the PCF8575 port expander.", "I2C address", "Allowed range 0x20-0x27.",
     false, false, 0x20, 0x20, 0x27},
    {"master", "pins.slaveTx", "slave_tx", "Slave UART TX",
     "UART link", "Transmit pin heading to the slave ESP.", "UART TX", "GPIO-only serial line.",
     false, true, Pins::SLAVE_UART_TX, 0, 39},
    {"master", "pins.slaveRx", "slave_rx", "Slave UART RX",
     "UART link", "Receive pin coming from the slave ESP.", "UART RX", "GPIO-only serial line.",
     false, true, Pins::SLAVE_UART_RX, 0, 39},
    {"master", "rcPins.0", "rc1", "RC channel 1 (steering)",
     "RC receiver", "Primary steering channel for the transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH1, 0, 39},
    {"master", "rcPins.1", "rc2", "RC channel 2 (throttle)",
     "RC receiver", "Throttle command channel for the transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH2, 0, 39},
    {"master", "rcPins.2", "rc3", "RC channel 3",
     "RC receiver", "Aux channel usually used for buttons.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH3, 0, 39},
    {"master", "rcPins.3", "rc4", "RC channel 4",
     "RC receiver", "Secondary switch or mode channel.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH4, 0, 39},
    {"master", "rcPins.4", "rc5", "RC channel 5",
     "RC receiver", "Reserved channel for auxiliary sensors.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH5, 0, 39},
    {"master", "rcPins.5", "rc6", "RC channel 6",
     "RC receiver", "Reserved channel for auxiliary sensors.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH6, 0, 39},
    {"slave", "pins.leftDriver.motorA.pwm", "leftMotorA_pwm", "Left motor A PWM",
     "Slave left driver", "Speed output for the front-left track on the slave board.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::LEFT_MOTOR1_PWM, 0, 39},
    {"slave", "pins.leftDriver.motorA.in1", "leftMotorA_in1", "Left motor A IN1",
     "Slave left driver", "Direction input A for the slave left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR1_IN1, 0, 39},
    {"slave", "pins.leftDriver.motorA.in2", "leftMotorA_in2", "Left motor A IN2",
     "Slave left driver", "Direction input B for the slave left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR1_IN2, 0, 39},
    {"slave", "pins.leftDriver.motorB.pwm", "leftMotorB_pwm", "Left motor B PWM",
     "Slave left driver", "Speed output for the rear-left track on the slave board.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::LEFT_MOTOR2_PWM, 0, 39},
    {"slave", "pins.leftDriver.motorB.in1", "leftMotorB_in1", "Left motor B IN1",
     "Slave left driver", "Direction input A for the slave rear-left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR2_IN1, 0, 39},
    {"slave", "pins.leftDriver.motorB.in2", "leftMotorB_in2", "Left motor B IN2",
     "Slave left driver", "Direction input B for the slave rear-left track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::LEFT_MOTOR2_IN2, 0, 39},
    {"slave", "pins.leftDriver.standby", "leftDriver_stby", "Left driver standby",
     "Slave left driver", "Standby pin used to enable the slave TB6612 driver.", "Digital output", "GPIO-only driver enable.",
     false, true, Pins::LEFT_DRIVER_STBY, 0, 39},
    {"slave", "pins.rightDriver.motorA.pwm", "rightMotorA_pwm", "Right motor A PWM",
     "Slave right driver", "Speed output for the front-right track on the slave board.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::RIGHT_MOTOR1_PWM, 0, 39},
    {"slave", "pins.rightDriver.motorA.in1", "rightMotorA_in1", "Right motor A IN1",
     "Slave right driver", "Direction input A for the slave right front track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR1_IN1, 0, 39},
    {"slave", "pins.rightDriver.motorA.in2", "rightMotorA_in2", "Right motor A IN2",
     "Slave right driver", "Direction input B for the slave right front track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR1_IN2, 0, 39},
    {"slave", "pins.rightDriver.motorB.pwm", "rightMotorB_pwm", "Right motor B PWM",
     "Slave right driver", "Speed output for the rear-right track on the slave board.", "PWM output", "GPIO-only PWM output.",
     false, true, Pins::RIGHT_MOTOR2_PWM, 0, 39},
    {"slave", "pins.rightDriver.motorB.in1", "rightMotorB_in1", "Right motor B IN1",
     "Slave right driver", "Direction input A for the slave rear-right track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR2_IN1, 0, 39},
    {"slave", "pins.rightDriver.motorB.in2", "rightMotorB_in2", "Right motor B IN2",
     "Slave right driver", "Direction input B for the slave rear-right track.", "Direction input", "GPIO or PCA pin.",
     true, false, Pins::RIGHT_MOTOR2_IN2, 0, 39},
    {"slave", "pins.rightDriver.standby", "rightDriver_stby", "Right driver standby",
     "Slave right driver", "Standby pin used to enable the slave right TB6612 driver.", "Digital output", "GPIO-only driver enable.",
     false, true, Pins::RIGHT_DRIVER_STBY, 0, 39},
    {"slave", "pins.lightBar", "light_pin", "Light bar PWM",
     "Slave lighting", "PCA9685 channel for the slave light bar.", "Lighting", "GPIO or PCA pin.",
     true, false, Pins::LIGHT_BAR, 0, 39},
    {"slave", "pins.speaker", "speaker_pin", "Sound output",
     "Slave sound FX", "Speaker output used by the slave sound controller.", "Audio output", "GPIO or PCA pin.",
     true, false, Pins::SPEAKER, 0, 39},
    {"slave", "pins.batterySense", "battery_pin", "Battery sense",
     "Slave battery monitor", "Analog pin used to monitor the slave battery.", "Analog input", "GPIO or PCA pin.",
     true, false, Pins::BATTERY_SENSE, 0, 39},
    {"slave", "pins.pcfAddress", "pcfAddress", "PCF8575 address",
     "Slave IO expander", "I2C address for the PCF8575 port expander on the slave board.", "I2C address", "Allowed range 0x20-0x27.",
     false, false, 0x20, 0x20, 0x27},
    {"slave", "pins.slaveTx", "slave_tx", "Slave UART TX",
     "Slave UART link", "Transmit pin heading to the master ESP.", "UART TX", "GPIO-only serial line.",
     false, true, Pins::SLAVE_UART_TX, 0, 39},
    {"slave", "pins.slaveRx", "slave_rx", "Slave UART RX",
     "Slave UART link", "Receive pin coming from the master ESP.", "UART RX", "GPIO-only serial line.",
     false, true, Pins::SLAVE_UART_RX, 0, 39},
    {"slave", "rcPins.0", "rc1", "RC channel 1 (steering)",
     "Slave RC receiver", "Primary steering channel for the slave transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH1, 0, 39},
    {"slave", "rcPins.1", "rc2", "RC channel 2 (throttle)",
     "Slave RC receiver", "Throttle command channel for the slave transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH2, 0, 39},
    {"slave", "rcPins.2", "rc3", "RC channel 3",
     "Slave RC receiver", "Aux buttons for the slave transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH3, 0, 39},
    {"slave", "rcPins.3", "rc4", "RC channel 4",
     "Slave RC receiver", "Mode switch channel for the slave transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH4, 0, 39},
    {"slave", "rcPins.4", "rc5", "RC channel 5",
     "Slave RC receiver", "Reserved sensor channel for the slave transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH5, 0, 39},
    {"slave", "rcPins.5", "rc6", "RC channel 6",
     "Slave RC receiver", "Reserved sensor channel for the slave transmitter.", "RC channel", "Analog input range 0-39.",
     false, false, Pins::RC_CH6, 0, 39},
};

constexpr std::size_t kPinSchemaCount = sizeof(kPinSchema) / sizeof(kPinSchema[0]);
}  // namespace TankRC::Config
